### ISSUE TITLE
Question about how to generate adj.npy of pems08.

### ISSUE THREAD

**Issue by packer-c** [wenhaomin/DiffSTG#2]
Hi, thanks for your nice work and code.

I saw you provided the adj.npy file. I would like to know how you generated the adj.npy. Could you provide some references code or repo?

Looking forward to your reply. Thanks in advance!

**Comment by wenhaomin** [comment]
Thanks for your question. We compute the Euclidean distances between monitoring stations and construct a weighted adjacency matrix using a thresholded Gaussian kernel:
<img width="312" alt="image" src="https://github.com/wenhaomin/DiffSTG/assets/20921601/2654326a-2351-4d4c-86ce-7dd5ff89417a">

**Comment by cifang-Kasit** [comment]
Hi. Thank you for your nice work and organized code.

As it mentioned previously, the adj is calculated by the Euclidean distances between stations.

However, the attached adj.npy file seems only contains binary value (0 or 1). 

May I ask how can I solve this problem? Will it influence the performance of the spatial information obtain?

Looking forward to your reply. It is a really nice work. Thanks in advance! 
![image](https://github.com/wenhaomin/DiffSTG/assets/74644912/a17921d2-038b-4f27-abeb-c568f2de6d29)

To make a comparison, another adj.npy example from STGCN is attached.

![image](https://github.com/wenhaomin/DiffSTG/assets/74644912/74bfb5c9-220c-4cf1-adf2-41801e2f544c)

**Comment by wenhaomin** [comment]
Hi, Thanks for your question. The model can support both weighted adj and binary adj. We are sorry for the unclear clarification in previous anser. In our setting, the adj of  air dataset is caluated by the Euclidean distances. And for the PEMS, we directly use the adj from previous works. Thanks~
