### ISSUE TITLE
Details about the code for the sample strategy

### ISSUE THREAD

**Issue by Wanghkkkkkkk** [wenhaomin/DiffSTG#3]
Hi, @wenhaomin 
     I was studying your code and noticed that you use three methods in the sample_strategy, namely 'ddim_multi', 'ddim_one' and 'ddpm'. I would like to ask which method is used in the paper?
     Looking forward to your reply, thank you!

**Comment by Wanghkkkkkkk** [comment]
And why use ‘ddpm’ when training and ‘ddim_multi’ when testing in code?

**Comment by wenhaomin** [comment]
Hi, thanks for the question. ddim_multi is used in the method.
For sample strategy, to estimate the data distribution from a trained model, i.e., getting S samples.
- ddpm needs to samling S*N diffusion steps;   
- ddim needs to sample S * M (M < N) diffusion steps;  
- ddim_multi need  (S/k) * M diffusion steps, where k is the number of samples used in one reverse process.   
 
So ddim_multi can be used in test for its sampling speed is much faster.

**Comment by Wanghkkkkkkk** [comment]
So, using ddim_multi during training will also make it faster, right?
