### ISSUE TITLE
未改动代码，训练时只能1个epoch

### ISSUE THREAD

**Issue by w2obin** [wenhaomin/DiffSTG#5]
作者您好，我在下载代码后，发现代码只能跑1个epoch，请问我应该修改哪里的设置呢？

这是部分log信息：

`    )
    (x_proj): Conv2d(1, 32, kernel_size=(1, 1), stride=(1, 1))
    (out): Sequential(
      (0): Conv2d(32, 1, kernel_size=(1, 1), stride=(1, 1))
      (1): Linear(in_features=48, out_features=24, bias=True)
    )
  )
)Num_of_parameters:996793
      |---Train--- |---Val Future-- -|-----Val History----|
Epoch | Loss  Time | MAE     RMSE    |  MAE    RMSE   Time|
   0.0| 13.465 1.4s |[3053.835266.22] | 3486.215907.7718.82s
   1.0| 10.413 0.2s | 3057.715184.08 | 2838.404929.9218.89s
best model loaded from: << /home/wbq/robstg/baselines/DiffSTG-main/output/model/UGnet+32+200+quad+0.1+200+ddpm+12+8+True+PEMS08+0.0+True+False+0.002+8N-200+T_h-12+T_p-12+epsilon_theta-UGnet.dm4stg
 |[361.13 461.42 ] | 442.56 581.50 33.59s
sample_strategy:ddim_multi, sample_steps:40 Final results in test:361.13 461.42 242.12 0.82    2016.43 | 3    
/home/wbq/anaconda3/lib/python3.8/site-packages/json_tricks/encoders.py:367: UserWarning: json-tricks: numpy scalar serialization is experimental and may work differently in future versions
  warnings.warn('json-tricks: numpy scalar serialization is experimental and may work differently in future versions')
[2024-09-28 07:25:25] INFO (nni/MainThread) Final result: 361.12847900390625`

**Comment by wenhaomin** [comment]
你好，可以修改train中的is_test参数

**Comment by w2obin** [comment]
您好，非常感谢您的指导。
我把is_test修改后，代码一直停留在：
Epoch | Loss  Time | MAE     RMSE    |  MAE    RMSE   Time|
   1.0| 1.819 51.9s
 很长时间，我不知道这是否正常。

后来我把is_test相关的代码注释掉后，可以开始正常运行，取得的结果是：
175.0| 0.444 50.6s | 21.86  32.07   | 1.23   1.55   19.00s
 176.0| 0.444 50.6s | 21.85  32.06   | 1.23   1.55   19.00s
 177.0| 0.444 50.6s | 21.84  32.05   | 1.23   1.55   19.00s
 178.0| 0.444 50.6s | 21.84  32.04   | 1.23   1.55   19.00s
 179.0| 0.444 50.6s | 21.84  32.04   | 1.23   1.55   19.01s
predict_path = '/home/baselines/DiffSTG-main/output/forecast/UGnet+32+200+quad+0.1+200+ddpm+12+8+True+PEMS08+0.0+True+False+0.002+8.pkl'
 |[29.37  40.07  ] | 0.33   0.51   33.71s
sample_strategy:ddim_multi, sample_steps:40 Final results in test:29.37  40.07  11.92  0.08    456.28  | 179  

但最终结果和论文结果差距比较大。
因此想劳烦您再指点一下，非常感谢！

**Comment by yejinxueshi** [comment]
> 您好，非常感谢您的指导。 我把is_test修改后，代码一直停留在： Epoch | Loss Time | MAE RMSE | MAE RMSE Time| 1.0| 1.819 51.9s 很长时间，我不知道这是否正常。
> 
> 后来我把is_test相关的代码注释掉后，可以开始正常运行，取得的结果是： 175.0| 0.444 50.6s | 21.86 32.07 | 1.23 1.55 19.00s 176.0| 0.444 50.6s | 21.85 32.06 | 1.23 1.55 19.00s 177.0| 0.444 50.6s | 21.84 32.05 | 1.23 1.55 19.00s 178.0| 0.444 50.6s | 21.84 32.04 | 1.23 1.55 19.00s 179.0| 0.444 50.6s | 21.84 32.04 | 1.23 1.55 19.01s predict_path = '/home/baselines/DiffSTG-main/output/forecast/UGnet+32+200+quad+0.1+200+ddpm+12+8+True+PEMS08+0.0+True+False+0.002+8.pkl' |[29.37 40.07 ] | 0.33 0.51 33.71s sample_strategy:ddim_multi, sample_steps:40 Final results in test:29.37 40.07 11.92 0.08 456.28 | 179
> 
> 但最终结果和论文结果差距比较大。 因此想劳烦您再指点一下，非常感谢！

请问您解决了这个吗，我也无法复现出论文中的结果

**Comment by kanosa0101** [comment]
我也
